/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type Color = string;

export interface Animal {
  name: string;
  fill?: Color;
  stroke?: Color;
  "stroke-width"?: number;
  close?: boolean;
  segments: {
    constraints: {
      radius: number;
      angle: number;
    };
    draw?: (
      | {
          type: "point";
          place: Point;
        }
      | {
          type: "circle";
          radius: number;
          fill?: Color;
          stroke?: Color;
          "stroke-width"?: number;
          place?: Point;
        }
    )[];
    anchors?: {
      forward?: Point[];
      backward?: Point[];
    };
    repeat?: number;
  }[];
}
export interface Point {
  radius: number;
  angle: number;
}
